<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TargetFrameworks>net8.0</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CommandLineParser" Version="2.9.1"/>
        <PackageReference Include="DTDLParser" Version="1.0.12-preview-ge5017bcd00"/>
        <PackageReference Include="System.Linq.Async" Version="6.0.1"/>
    </ItemGroup>

</Project>
