<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TargetFrameworks>net8.0</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CommandLineParser" Version="2.9.1"/>
        <PackageReference Include="Microsoft.Azure.DigitalTwins.Parser" Version="6.4.0-preview"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="output\"/>
    </ItemGroup>

</Project>
